# Generated by Django 2.1.5 on 2019-01-24 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190124_1727'),
        ('shop', '0005_auto_20190123_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 15, 27, 54, 859569, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
